### ISSUE TITLE
License

### ISSUE THREAD

**Issue by typemytype** [loicsander/MutatorScale#1]
Could you also embed the license text from the booleanglyph package

Thanks

**Comment by loicsander** [comment]
Could, and should, well spotted, I moved too fast on that one! It’s done: added license in booleanOperations folder and added BooleanOperations to dependencies’ list in Readme.

**Comment by typemytype** [comment]
thanks

**Comment by davelab6** [comment]
What about the license for the overall repo?

**Comment by loicsander** [comment]
Oh yeah, I suck at handling licenses, there, MIT.

**Comment by adrientetar** [comment]
@loicsander Just wondering but why do you embed these packages instead of using them as external deps?

**Comment by loicsander** [comment]
Because that’s the way I felt confortable doing it, being able to move the package with as few depencies to install separately as possible.
